# Generated by Django 4.2 on 2023-04-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_participants', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('number_of_classes', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Prog', 'Programming'), ('Mark', 'Marketing'), ('Soft', 'Soft Skills')], default='Prog', max_length=4)),
            ],
        ),
    ]
