# Generated by Django 4.2 on 2023-04-07 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=2)),
                ('linkedin_link', models.URLField()),
                ('github_link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='instructor',
            name='age',
            field=models.CharField(max_length=2),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.course')),
                ('participantID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.participant')),
            ],
        ),
    ]
